---
- name: Check current frr_exporter version.
  command: "{{ frr_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: frr_exporter_version_check

- name: Configure latest version
  include_tasks: config-version.yaml
  when: >
    frr_exporter_version is match("latest")
    or frr_exporter_version is not defined

- name: Download and unarchive frr_exporter into temporary location.
  unarchive:
    src: "{{ frr_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0755
  when: >
    frr_exporter_version_check.stdout is not defined
    or frr_exporter_version not in frr_exporter_version_check.stdout
  register: frr_exporter_download_check

- name: Move frr_exporter binary into place.
  copy:
    src: "/tmp/frr_exporter-{{ frr_exporter_version }}.linux-{{ frr_exporter_arch }}/frr_exporter"
    dest: "{{ frr_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart frr_exporter
  when: >
    frr_exporter_download_check is changed
    or frr_exporter_version_check.stdout | length == 0

- name: Create frr_exporter user.
  user:
    name: frr_exporter
    shell: /sbin/nologin
    state: present

- name: Add frr_exporter user to frr group
  user:
    name: frr_exporter
    groups: frrvty

- name: Copy the frr_exporter systemd unit file.
  template:
    src: frr_exporter.service.j2
    dest: /etc/systemd/system/frr_exporter.service
    mode: 0644
  register: frr_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart frr_exporter
  when: frr_exporter_service is changed

- name: Ensure frr_exporter is running and enabled at boot.
  service:
    name: frr_exporter
    state: "{{ frr_exporter_state }}"
    enabled: "{{ frr_exporter_enabled }}"

- name: Verify frr_exporter is responding to requests.
  uri:
    url: "http://{% if frr_exporter_host !='' %}{{ frr_exporter_host }}{% else %}localhost{% endif %}:{{ frr_exporter_port }}/"
    return_content: true
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
